<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
*{box-sizing:border-box}body{margin:0;background:#f8f5ef;color:#2d211d;font-family:Arial,sans-serif}.site{width:1440px;background:#fff}.nav{height:94px;padding:0 74px;display:flex;align-items:center;justify-content:space-between;background:#fff}.brand{font-size:24px;font-weight:700;letter-spacing:.5px}.links{display:flex;gap:34px;font-size:15px}.links a{color:#2d211d;text-decoration:none}.nav .button{background:#24150f;color:#fff;padding:14px 24px;border-radius:8px;font-weight:700}.hero{min-height:470px;padding:100px 74px;background:{{ $design['primary_color'] ?? '#6f4328' }};color:#fff;position:relative;overflow:hidden}.hero:after{content:'';position:absolute;right:-100px;top:-160px;width:620px;height:620px;border-radius:50%;background:{{ $design['secondary_color'] ?? '#bd8a5f' }};opacity:.35}.hero h1{position:relative;z-index:1;max-width:700px;margin:0 0 24px;font-family:Georgia,serif;font-size:62px;line-height:1.08}.hero p{position:relative;z-index:1;max-width:620px;font-size:20px;line-height:1.6}.hero .button{position:relative;z-index:1;display:inline-block;margin-top:20px;background:#fff;color:{{ $design['primary_color'] ?? '#6f4328' }};padding:16px 25px;border-radius:8px;font-weight:700}.section{padding:72px 74px;text-align:center}.section.alt{background:#f4efe8}.eyebrow{color:#a16a46;font-size:13px;font-weight:700;letter-spacing:2px;text-transform:uppercase}.section h2{margin:10px 0 12px;font-family:Georgia,serif;font-size:36px}.section>p{max-width:620px;margin:0 auto;color:#756861;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;margin-top:38px;text-align:left}.card{border:1px solid #eadfd4;border-radius:10px;padding:25px;background:#fff}.card h3{margin:0 0 10px;font-size:18px}.card p{margin:0;color:#756861;line-height:1.55}.price{display:block;margin-top:15px;color:#a16a46;font-weight:700}.newsletter{margin:0 74px 72px;padding:38px 45px;text-align:center;background:#ead8c6;border-radius:12px}.newsletter h2{margin:0 0 8px;font-family:Georgia,serif}.footer{padding:44px 74px;background:#241b18;color:#fff;display:grid;grid-template-columns:2fr 1fr 1fr;gap:30px}.footer p{color:#d7c9c0;line-height:1.5}@media(max-width:700px){.site{width:100%}.nav{padding:0 24px}.links{display:none}.hero{padding:70px 24px}.hero h1{font-size:42px}.section{padding:54px 24px}.grid{grid-template-columns:1fr}.newsletter{margin:0 24px 54px}.footer{padding:35px 24px;grid-template-columns:1fr}}
</style>
</head>
<body><div class="site">
<header class="nav"><div class="brand">{{ $project->name }}</div><nav class="links"><a href="#home">Beranda</a><a href="#about">Tentang</a><a href="#services">Menu</a><a href="#gallery">Galeri</a><a href="#contact">Kontak</a></nav><span class="button">{{ $hero['cta'] ?? $mockup['global_cta'] ?? 'Pesan Sekarang' }}</span></header>
<section id="home" class="hero"><h1>{{ $hero['headline'] ?? $project->name }}</h1><p>{{ $hero['description'] ?? '' }}</p><span class="button">{{ $hero['cta'] ?? $mockup['global_cta'] ?? 'Beli Sekarang' }}</span></section>
@foreach (array_slice($homeSections, 1, 4) as $section)
<section id="{{ strtolower($section['type'] ?? 'section') }}" class="section {{ $loop->even ? 'alt' : '' }}"><span class="eyebrow">{{ $section['name'] ?? 'Tentang Kami' }}</span><h2>{{ $section['headline'] ?? $section['name'] ?? 'Section' }}</h2><p>{{ $section['description'] ?? '' }}</p>@if (!empty($section['items']) && is_array($section['items']))<div class="grid">@foreach (array_slice($section['items'],0,4) as $item)<article class="card"><h3>{{ is_array($item) ? ($item['title'] ?? $item['name'] ?? 'Item') : $item }}</h3>@if(is_array($item))<p>{{ $item['description'] ?? '' }}</p>@if(!empty($item['price']))<span class="price">{{ $item['price'] }}</span>@endif@endif</article>@endforeach</div>@endif</section>
@endforeach
<div class="newsletter"><h2>{{ $mockup['global_cta'] ?? 'Dapatkan promo &amp; sampel gratis' }}</h2><p>{{ data_get($newsletter ?? [], 'description', 'Daftar untuk mendapat informasi terbaru dari kami.') }}</p></div>
<footer id="contact" class="footer"><div><strong>{{ $project->name }}</strong><p>{{ $mockup['website_concept'] ?? '' }}</p></div><div><strong>Navigasi</strong><p>Beranda<br>Tentang<br>Menu<br>Galeri</p></div><div><strong>Kontak</strong><p>Hubungi kami untuk informasi dan pemesanan.</p></div></footer>
</div></body></html>
