<?php

namespace App\Services;

use ZipArchive;

class BundleExporterService
{
    public function export(array $bundle, string $outputDir): string
    {
        if (!is_dir($outputDir) && !mkdir($outputDir, 0777, true) && !is_dir($outputDir)) {
            throw new \RuntimeException('Folder export bundle tidak dapat dibuat.');
        }

        $zipPath = $outputDir . DIRECTORY_SEPARATOR . 'bundle-export.zip';

        $zip = new ZipArchive();
        $zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE);

        $wordpressFiles = $bundle['wordpress']['files'] ?? [];
        $componentFiles = ['theme' => [], 'plugin' => []];

        foreach ($wordpressFiles as $relativePath => $contents) {
            $zip->addFromString($relativePath, $contents);

            $component = str_starts_with($relativePath, 'elementor/')
                ? null
                : (str_contains($relativePath, '/theme/') || str_contains($relativePath, '-theme/') ? 'theme' : null);

            if ($component === null && preg_match('#^[^/]+/[^/]+\.php$#', $relativePath)) {
                $component = 'plugin';
            }

            if ($component) {
                $componentFiles[$component][$relativePath] = $contents;
            }
        }

        foreach ($componentFiles as $component => $files) {
            if (empty($files)) {
                continue;
            }

            $componentZip = tempnam(sys_get_temp_dir(), 'wp-bundle-');
            $componentArchive = new ZipArchive();
            $componentArchive->open($componentZip, ZipArchive::CREATE | ZipArchive::OVERWRITE);
            foreach ($files as $relativePath => $contents) {
                $componentArchive->addFromString($relativePath, $contents);
            }
            $componentArchive->close();
            $zip->addFile($componentZip, $component . '.zip');
        }

        $files = [
            'theme' => $bundle['theme'] ?? [],
            'plugin' => $bundle['plugin'] ?? [],
            'elementor' => $bundle['elementor'] ?? [],
            'assets' => $bundle['assets'] ?? [],
            'content' => $bundle['content'] ?? [],
        ];

        foreach ($files as $folder => $payload) {
            $zip->addFromString($folder . '/README.txt', "Bundle component: {$folder}\n");
            if (is_array($payload)) {
                foreach ($payload as $key => $value) {
                    if (is_array($value)) {
                        $json = json_encode($value, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
                        $zip->addFromString($folder . '/' . $key . '.json', $json);
                    } else {
                        $zip->addFromString($folder . '/' . $key . '.txt', (string) $value);
                    }
                }
            }
        }

        $zip->addFromString('README.md', "# WordPress Bundle\n\nThis package was generated by Exito bundle system.\n");
        $zip->close();

        return $zipPath;
    }
}
